services:

  # Mandatory
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
  # ---

  # Bonus
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - inception
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  static-website:
    build: ./requirements/bonus/static-website
    container_name: static-website
    ports:
      - "8080:80"
    networks:
      - inception
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  filebrowser:
    build: ./requirements/bonus/filebrowser
    container_name: filebrowser
    ports:
      - "9000:8082"
    env_file:
      - .env
    volumes:
      - wordpress_data:/srv:rw
      - filebrowser_data:/database
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress
  # ---
  
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress
  filebrowser_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/filebrowser

networks:
  inception:
    driver: bridge
